/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayerTurnPanel.java
 *
 * Created on Apr 12, 2011, 4:24:56 PM
 */

package c4n3.GUI;

/**
 *
 * @author Alexander Darino
 */
public class PlayerTurnPanel extends javax.swing.JPanel {

    /** Creates new form PlayerTurnPanel */
    public PlayerTurnPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerTurnLabel = new javax.swing.JLabel();
        playerTurnValueLabel = new javax.swing.JLabel();
        player1LastMoveLabel = new javax.swing.JLabel();
        player1LastMoveValueLabel = new javax.swing.JLabel();
        player2LastMoveLabel = new javax.swing.JLabel();
        player2LastMoveValueLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(3, 2));

        playerTurnLabel.setText("Player Turn:");
        add(playerTurnLabel);
        add(playerTurnValueLabel);

        player1LastMoveLabel.setText("Player 1's Last Move:");
        add(player1LastMoveLabel);
        add(player1LastMoveValueLabel);

        player2LastMoveLabel.setText("Player 2's Last Move:");
        add(player2LastMoveLabel);
        add(player2LastMoveValueLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel player1LastMoveLabel;
    private javax.swing.JLabel player1LastMoveValueLabel;
    private javax.swing.JLabel player2LastMoveLabel;
    private javax.swing.JLabel player2LastMoveValueLabel;
    private javax.swing.JLabel playerTurnLabel;
    private javax.swing.JLabel playerTurnValueLabel;
    // End of variables declaration//GEN-END:variables

    public void updateTurn(int playerID, String playerLastMove)
    {
        playerTurnValueLabel.setText(Integer.toString(1 + (playerID + 1) %2));
        if (playerID == 1) player1LastMoveValueLabel.setText(playerLastMove);
        else player2LastMoveValueLabel.setText(playerLastMove);
    }
}
